#!/usr/bin/env bash

sudo -v

echo "--- UPDATE ---"
sudo apt update

echo "--- UPGRADE ---"
sudo apt upgrade

echo "--- FULL-UPGRADE ---"
sudo apt full-upgrade

echo "--- CLEAN ---"
sudo apt clean

echo "--- AUTOREMOVE ---"
sudo apt autoremove
