export const SKYRECORDER_DATA = {
    timelapse: {
        '2019': {
            '01': { dur: '1:09:33', urls: ['https://youtube.com/watch?v=ALnCZ1REx6E'] },
            '02': { dur: '1:13:44', urls: ['https://youtube.com/watch?v=Zo5HH-QFbAs'] },
            // stopped the project 2019-02
        },
        '2018': {
            '01': { dur: '1:10:06', urls: ['https://youtube.com/watch?v=ynACvfs2cZM'] },
            '02': { dur: '1:12:12', urls: ['https://youtube.com/watch?v=x5DmPQuYqTU'] },
            '03': { dur: '1:33:10', urls: ['https://youtube.com/watch?v=yafaJPkiW88'] },
            '04': { dur: '1:45:02', urls: ['https://youtube.com/watch?v=xHnpYo0CRu4'] },
            '05': { dur: '1:57:11', urls: ['https://youtube.com/watch?v=D9cHGxKJvWw'] },
            '06': { dur: '2:01:57', urls: ['https://youtube.com/watch?v=IsciRPc892I'] },
            '07': { dur: '1:55:36', urls: ['https://youtube.com/watch?v=fupJN-uyEbc'] },
            '08': { dur: '1:50:09', urls: ['https://youtube.com/watch?v=MLWhfZazxcc'] },
            '09': { dur: '1:36:01', urls: ['https://youtube.com/watch?v=QjjKQTd-MCE'] },
            '10': { dur: '1:25:56', urls: ['https://youtube.com/watch?v=1FJHkjQhDkg'] },
            '11': { dur: '1:08:44', urls: ['https://youtube.com/watch?v=vi7TEGWzPHI'] },
            '12': { dur: '59:56', urls: ['https://youtube.com/watch?v=TGK5DJg0-7M'] },
        },
        '2017': {
            '01': { dur: '1:26:58', urls: ['https://youtube.com/watch?v=8-Mn4Tj3_Oc'] },
            '02': { dur: '1:24:59', urls: ['https://youtube.com/watch?v=90GO1DAIuQU'] },
            '03': { dur: '1:34:42', urls: ['https://youtube.com/watch?v=qZaZyx7TVdc'] },
            '04': { dur: '1:46:03', urls: ['https://youtube.com/watch?v=B5QggwCqewM'] },
            '05': { dur: '1:58:48', urls: ['https://youtube.com/watch?v=6s1KnQMyuZU'] },
            '06': { dur: '2:01:02', urls: ['https://youtube.com/watch?v=tULJ0tvxFFs'] },
            '07': { dur: '2:01:55', urls: ['https://youtube.com/watch?v=7tLA7-TjlRI'] },
            '08': { dur: '1:53:47', urls: ['https://youtube.com/watch?v=CqwLoJCanHA'] },
            '09': { dur: '1:36:33', urls: ['https://youtube.com/watch?v=S_iD3j7231E'] },
            '10': { dur: '1:25:46', urls: ['https://youtube.com/watch?v=RPG9Pgi7QdA'] },
            '11': { dur: '1:08:06', urls: ['https://youtube.com/watch?v=aPQ1sou6qKY'] },
            '12': { dur: '1:06:46', urls: ['https://youtube.com/watch?v=gsmWSbZk6Xg'] },
        },
        '2016': {
            '01': { dur: '1:25:05', urls: ['https://youtube.com/watch?v=5uZuIKPH76Q'] },
            '02': { dur: '1:26:31', urls: ['https://youtube.com/watch?v=rT6x9V-VPPA'] },
            '03': { dur: '1:47:09', urls: ['https://youtube.com/watch?v=WdHAbUoVOS0'] },
            '04': { dur: '1:58:23', urls: ['https://youtube.com/watch?v=a3QtVHGQm34'] },
            '05': { dur: '2:14:21', urls: ['https://youtube.com/watch?v=MxQLeYjwFoA'] },
            '06': { dur: '1:30:27', urls: ['https://youtube.com/watch?v=apuMVH4xln0'] },
            '07': { dur: '2:26:28', urls: ['https://youtube.com/watch?v=nmlonxpYx4M'] },
            '08': { dur: '1:52:35', urls: ['https://youtube.com/watch?v=f8DV2vNIUAg'] },
            // '09': { dur: '', urls: [] }, // moved to new home
            // '10': { dur: '', urls: [] }, // moved to new home
            '11': { dur: '1:26:09', urls: ['https://youtube.com/watch?v=poOABYV-DM8'] },
            '12': { dur: '1:29:40', urls: ['https://youtube.com/watch?v=MvmO99Q_JgU'] },
        },
        '2015': {
            '01': { dur: '9:34', urls: ['https://youtube.com/watch?v=DbgBC2lNhcM'] },
            '02': { dur: '9:38', urls: ['https://youtube.com/watch?v=dzdLd46hOGU'] },
            '03': { dur: '11:55', urls: ['https://youtube.com/watch?v=W71SgI4TZeU'] },
            '04': { dur: '13:07', urls: ['https://youtube.com/watch?v=H-xIH9xXK40'] },
            '05': { dur: '14:58', urls: ['https://youtube.com/watch?v=plgNEQnQl5k'] },
            '06': { dur: '15:11', urls: ['https://youtube.com/watch?v=QSNv-VQzTbA'] },
            '07': { dur: '15:25', urls: ['https://youtube.com/watch?v=BjesGMuFKi8'] },
            '08': { dur: '14:22', urls: ['https://youtube.com/watch?v=RbD1C4PQqqo'] },
            '09': { dur: '12:41', urls: ['https://youtube.com/watch?v=pSfqyZEYWX8'] },
            '10': { dur: '11:37', urls: ['https://youtube.com/watch?v=XEHXk3SqFPs'] },
            '11': { dur: '10:07', urls: ['https://youtube.com/watch?v=MULoM1sbe4A'] },
            '12': { dur: '10:13', urls: ['https://youtube.com/watch?v=EaG3sPj8R_4'] },
        },
        '2014': {
            '01': { dur: '9:32', urls: ['https://youtube.com/watch?v=dorM5kHshy8'] },
            '02': { dur: '9:07', urls: ['https://youtube.com/watch?v=6P-XsWNxmjY'] },
            '03': { dur: '12:02', urls: ['https://youtube.com/watch?v=jUkY0gEWFtE'] },
            '04': { dur: '12:40', urls: ['https://youtube.com/watch?v=I9wwHb1EssQ'] },
            '05': { dur: '14:40', urls: ['https://youtube.com/watch?v=2EqEvWwmOJY'] },
            '06': { dur: '15:08', urls: ['https://youtube.com/watch?v=cOpLbBwbcVo'] },
            '07': { dur: '15:14', urls: ['https://youtube.com/watch?v=6EH8Hx1WZWk'] },
            '08': { dur: '14:43', urls: ['https://youtube.com/watch?v=r7OEdnflZSw'] },
            '09': { dur: '12:28', urls: ['https://youtube.com/watch?v=5MMjxGwDtsE'] },
            '10': { dur: '11:29', urls: ['https://youtube.com/watch?v=_AStswZ9Xy8'] },
            '11': { dur: '9:55', urls: ['https://youtube.com/watch?v=O87NZvpERP0'] },
            '12': { dur: '9:28', urls: ['https://youtube.com/watch?v=F-kRkktYUIc'] },
        },
        '2013': {
            '07': { dur: '15:28', urls: ['https://youtube.com/watch?v=LVZ6htJ7q6E'] },
            '08': { dur: '14:05', urls: ['https://youtube.com/watch?v=xEvmoTnK2Jg'] },
            '09': { dur: '12:09', urls: ['https://youtube.com/watch?v=Ju-DjHnafpY'] },
            '10': { dur: '11:10', urls: ['https://youtube.com/watch?v=HaWV6NeiSl8'] },
            '11': { dur: '10:03', urls: ['https://youtube.com/watch?v=Xbb_4QwxSQk'] },
            '12': { dur: '9:43', urls: ['https://youtube.com/watch?v=gFVJSycmFj0'] },
        },
    },
}
